services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ai-network
    restart: unless-stopped

  api:
    build: ./api
    container_name: government-ai-api
    ports:
      - "3000:3000"
    volumes:
      - ./api/config:/app/config
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ai-network
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local

networks:
  ai-network:
    driver: bridge
